//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetails_T
    {
        public int BillDetailsID { get; set; }
        public Nullable<int> FleetCompanyID { get; set; }
        public Nullable<int> BillID { get; set; }
        public Nullable<int> ServicePartsID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
