//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_T
    {
        public int BillID { get; set; }
        public Nullable<int> FleetCompanyID { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<int> ShopID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public string Odometer { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
    }
}
