//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetCompany_T
    {
        public int FleetCompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public string Website { get; set; }
        public string ContactPerson { get; set; }
        public string Mobile { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public Nullable<bool> Activated { get; set; }
        public string SPID { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
    }
}
