//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPerson_T
    {
        public int SalesPersonID { get; set; }
        public Nullable<System.Guid> UniqueID { get; set; }
        public string SPID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
    }
}
