//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrafficContraventions_T
    {
        public int TrafficContraventionID { get; set; }
        public Nullable<int> FleetCompanyID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> TrafficContraventionDate { get; set; }
        public string Description { get; set; }
    }
}
