//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleType_T
    {
        public int VehicleTypeID { get; set; }
        public Nullable<int> FleetCompanyID { get; set; }
        public string VehicleType { get; set; }
    }
}
